### ISSUE TITLE
Please support H3s

### ISSUE THREAD

**Issue by boosh** [frysztak/markdown-to-quill-delta#4]
I assume [this](https://github.com/frysztak/markdown-to-quill-delta/blob/e458aa04f1462dea0a86e4c075eb45b3c8582d86/src/markdownToDelta.ts#L94) just needs changing to:
```
  const headingVisitor = (node: any) => {
    const mapSize = (depth: number): string => {
      switch (depth) {
        case 1:
          return "huge";
        case 2:
          return "large";
        case 3:
          return "small";
        default:
          return "large";
      }
    };

    const size = mapSize(node.depth);
    paragraphVisitor({ attributes: { size: size } })(node);
  };
```
It'd be great if you could add support for this please. It seems quill supports [up to H6](https://github.com/slab/quill/blob/main/packages/quill/src/formats/header.ts), so you might want to add more levels too.

This lib is  lifesaver. Thanks!

**Comment by frysztak** [comment]
I won't be able to do that, but PRs are more than welcome

**Comment by boosh** [comment]
Great. I was literally just working on one: #6.

Thanks

**Comment by frysztak** [comment]
thank you @boosh, I just pushed v0.8.0 with your PR

**Comment by rxliuli** [comment]
Why use `"size": "huge"` instead of `"header": 1`? I'm also trying to convert markdown to quill delta, but I'm not sure why this conversion is necessary, as the header property is indeed supported.

**Comment by boosh** [comment]
Yeah I know. It should really use header but I didn't want to break backwards compatibility. 

@frysztak could we do a 1.0 that uses header instead of size? Ideally it'd accept options to define which style to use, but that's probably more than I could do atm...

**Comment by rxliuli** [comment]
Also, inlineCode is set to `font: monospace` instead of `code: true`, maybe this library hasn't caught up with the latest version of quill delta?

Example:

```md
`super code`
```

Expected:

```json
[
  {
    "attributes": {
      "code": true
    },
    "insert": "super code"
  },
  {
    "insert": "\n"
  }
]
```

Received:

```json
[
  {
    "attributes": {
      "font": "monospace"
    },
    "insert": "super code"
  },
  {
    "insert": "\n"
  }
]
```

**Comment by rxliuli** [comment]
There are also some strange empty line issues that make the conversion particularly unsuitable for web novels. Because usually, there is an empty line between each sentence in web novels, and the conversion defaults to turning empty lines into extra `{ "insert": "\n" }`. For example

https://github.com/frysztak/markdown-to-quill-delta/blob/master/test/mixed/01-two-paragraphs.md
https://github.com/frysztak/markdown-to-quill-delta/blob/master/test/mixed/01-two-paragraphs.json

**Comment by boosh** [comment]
Yeah. I strip those out after creating the delta with this library (as well as converting  `size` to `heading`). It'd be good to get full support for the latest delta (I think the README says block quotes also aren't supported). I'm not sure why there's not an official lib for this tbh, it must be a common use case.

**Comment by rxliuli** [comment]
I am forking this repository and making many modifications, including the issues mentioned above, as well as replacing and upgrading the libraries used (e.g. jest => vitest). Are you considering accepting PRs?
